CREATE TABLE IF NOT EXISTS courses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT REFERENCES departments(id) ON DELETE CASCADE NOT NULL,
    course_code VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) UNIQUE NOT NULL,
    credits INT NOT NULL DEFAULT 3,
    overview VARCHAR(255),
    course_level INT CHECK (course_level > 99) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS modules (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id  INT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
    title VARCHAR(255) NOT NULL,
    is_visible BOOLEAN DEFAULT TRUE,
    module_order INT DEFAULT 0 CHECK (module_order >= 0),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_course_module UNIQUE (title, course_id)
);

CREATE TABLE IF NOT EXISTS lessons (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id INT REFERENCES modules(id) ON DELETE CASCADE  NOT NULL,
    title VARCHAR(255) UNIQUE NOT NULL,
    lesson_order INT CHECK (lesson_order >= 0) DEFAULT 0,
    format VARCHAR(255) CHECK (format IN ('LINK', 'PDF', 'TEXT', 'VIDEO', 'IMAGE', 'SLIDE')),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_module_lesson UNIQUE (title, module_id)
);

CREATE TABLE IF NOT EXISTS prerequisites (
    course_id INT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
    dependon_id INT REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT pk_prerequisite PRIMARY KEY (course_id, dependon_id) 
);