CREATE TABLE IF NOT EXISTS universities( 
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    website_url VARCHAR(50) NOT NULL, 
    short_name VARCHAR(10) NOT NULL, 
    name VARCHAR(50) UNIQUE NOT NULL,
    address VARCHAR(50),
    email VARCHAR(30),
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS departments ( 
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(50) NOT NULL,
    university_id INT REFERENCES universities(id) ON DELETE CASCADE NOT NULL,
    building VARCHAR(50),
    phone VARCHAR(20), 
    department_code VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_university_department UNIQUE(name, university_id)
);

CREATE TABLE IF NOT EXISTS programs ( 
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    department_id INT REFERENCES departments(id) ON DELETE CASCADE NOT NULL,
    program_code VARCHAR(20) NOT NULL, 
    name VARCHAR(50) NOT NULL,
    degree VARCHAR(50) NOT NULL CHECK (degree IN ('Bachelor', 'Master', 'PhD')),
    duration_year INT DEFAULT 4,
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_department_program UNIQUE(name, department_id)
);


