CREATE TABLE IF NOT EXISTS universities( 
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    website_url VARCHAR(255) NOT NULL, 
    short_name VARCHAR(255) NOT NULL, 
    name VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS departments ( 
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR(255) NOT NULL,
    university_id INT REFERENCES universities(id) ON DELETE CASCADE NOT NULL,
    building VARCHAR(255),
    phone VARCHAR(255), 
    department_code VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_university_department UNIQUE(name, university_id)
);

CREATE TABLE IF NOT EXISTS programs ( 
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    department_id INT REFERENCES departments(id) ON DELETE CASCADE NOT NULL,
    program_code VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL,
    degree VARCHAR(255) NOT NULL CHECK (degree IN ('Bachelor', 'Master', 'PhD')),
    duration_year INT DEFAULT 4,
    created_at TIMESTAMP DEFAULT NOW(),
    update_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT unique_department_program UNIQUE(name, department_id)
);

ALTER TABLE programs ADD COLUMN is_active BOOLEAN DEFAULT TRUE;