INSERT INTO universities(id, website_url, short_name, name, address, email) 
VALUES
('ciu.edu.tr', 'CIU', 'Cyprus International University', 'Haspolat KKTC', 'ciu@edu.tr'),
('metu.edu.tr', 'METU', 'Middle East Technical University', 'Ankara, Türkiye', 'info@metu.edu.tr'),
('bilkent.edu.tr', 'BILKENT', 'Bilkent University', 'Ankara, Türkiye', 'contact@bilkent.edu.tr'),
('ktu.edu.tr', 'KTU', 'Karadeniz Technical University', 'Trabzon, Türkiye', 'info@ktu.edu.tr'),
('neu.edu.tr', 'NEU', 'Near East University', 'Nicosia, Cyprus', 'info@neu.edu.tr'),
('emu.edu.tr', 'EMU', 'Eastern Mediterranean University', 'Famagusta, Cyprus', 'info@emu.edu.tr'),
('istanbul.edu.tr', 'IU', 'Istanbul University', 'Istanbul, Türkiye', 'contact@istanbul.edu.tr'),
('hacettepe.edu.tr', 'HACETTEPE', 'Hacettepe University', 'Ankara, Türkiye', 'info@hacettepe.edu.tr'),
('ankara.edu.tr', 'ANKARAU', 'Ankara University', 'Ankara, Türkiye', 'info@ankara.edu.tr'),
('ege.edu.tr', 'EGE', 'Ege University', 'Izmir, Türkiye', 'info@ege.edu.tr'),
('sabanciuniv.edu', 'SU', 'Sabanci University', 'Istanbul, Türkiye', 'info@sabanciuniv.edu'),
('ku.edu.tr', 'KU', 'Koç University', 'Istanbul, Türkiye', 'contact@ku.edu.tr'),
('ytu.edu.tr', 'YTU', 'Yilidz Technical University', 'Istanbul, Türkiye', 'info@ytu.edu.tr'),
('bau.edu.tr', 'BAU', 'Bahçeşehir University', 'Istanbul, Türkiye', 'info@bau.edu.tr'),
('osmangazi.edu.tr', 'ESOGU', 'Osmangazi University', 'Eskişehir, Türkiye', 'info@osmangazi.edu.tr');

INSERT INTO departments (name, building, phone, department_code, university_id)  
VALUES
('Computer Engineering', 'ST', '+9053629137', 'CMPE', ),
('Electrical Engineering', 'EE', '+9053629001', 'EELE'),
('Mechanical Engineering', 'ME', '+9053629002', 'MECH'),
('Civil Engineering', 'CE', '+9053629003', 'CIVL'),
('Information Technology', 'IT', '+9053629004', 'ITEC'),
('Software Engineering', 'SW', '+9053629005', 'SWEN'),
('Business Administration', 'BU', '+9053629006', 'BUSN'),
('Marketing', 'MK', '+9053629007', 'MARK'),
('Chemistry', 'CH', '+9053629008', 'CHEM'),
('Physics', 'PH', '+9053629009', 'PHYS'),
('Mathematics', 'MA', '+9053629010', 'MATH'),
('Architecture', 'AR', '+9053629011', 'ARCH'),
('Dentistry', 'DN', '+9053629012', 'DENT'),
('Nursing', 'NU', '+9053629013', 'NURS'),
('Human Resources', 'HR', '+9053629014', 'HRES');

INSERT INTO program (department_id, program_code, name, degree, duration_year) 
VALUES
('AIEN201', 'Artificial Intelligence Programming', 'Artificial Intelligence Engineering', 4),
('CMPE301', 'Embedded Systems', 'Computer Engineering', 4),
('EELE210', 'Power Systems Engineering', 'Electrical Engineering', 4),
('EELE315', 'Control Systems', 'Electrical Engineering', 4),
('MECH220', 'Thermal Engineering', 'Mechanical Engineering', 4),
('MECH330', 'Automotive Engineering', 'Mechanical Engineering', 4),
('CIVL250', 'Structural Engineering', 'Civil Engineering', 4),
('CIVL340', 'Construction Management', 'Civil Engineering', 4),
('ITEC110', 'Information Systems', 'Information Technology', 4),
('ITEC205', 'Network Security', 'Information Technology', 4),
('SWEN200', 'Software Analysis and Design', 'Software Engineering', 4),
('SWEN340', 'Web & Mobile Development', 'Software Engineering', 4),
('BUSN101', 'General Business Administration', 'Business Administration', 4),
('BUSN220', 'Accounting & Finance', 'Business Administration', 4),
('MARK115', 'Digital Marketing', 'Marketing', 4),
('MARK250', 'Brand Management', 'Marketing', 4),
('CHEM100', 'Applied Chemistry', 'Chemistry', 4),
('CHEM210', 'Biochemistry', 'Chemistry', 4),
('PHYS130', 'Applied Physics', 'Physics', 4),
('PHYS260', 'Quantum Mechanics', 'Physics', 4),
('MATH150', 'Applied Mathematics', 'Mathematics', 4),
('MATH320', 'Statistics & Probability', 'Mathematics', 4),
('ARCH101', 'Architectural Design', 'Architecture', 5),
('ARCH330', 'Urban Planning', 'Architecture', 5),
('DENT110', 'General Dentistry', 'Dentistry', 5),
('DENT340', 'Oral Surgery', 'Dentistry', 5),
('NURS120', 'Clinical Nursing', 'Nursing', 4),
('NURS240', 'Emergency Care Nursing', 'Nursing', 4),
('HRES150', 'Human Resources Management', 'Human Resources', 4),
('HRES260', 'Organizational Behavior', 'Human Resources', 4);
