CREATE TABLE IF NOT EXISTS transcripts(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
student_id INT REFERENCES students (id),
gpa  float,
cgpa  float
);
CREATE TABLE IF NOT EXISTS course_results(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_id INT REFERENCES courses(id),
transcript_id INT REFERENCES transcripts(id),
grade float
);
CREATE TABLE IF NOT EXISTS tests (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
type  varchar(50) NOT NULL,
percentage    float
);

CREATE TABLE IF NOT EXISTS test_results( 
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_result_id INT REFERENCES  course_results(id),
test_result_id     INT REFERENCES tests(id),
grade    float 
);