CREATE TABLE IF NOT EXISTS transcripts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL REFERENCES students (id),
    gpa  float DEFAULT 0 CHECK (gpa BETWEEN 0 AND 4),
    cgpa  float DEFAULT 0  CHECK (cgpa BETWEEN 0 AND 4),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS course_results (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transcript_id INT NOT NULL REFERENCES transcripts(id),
    course_id INT NOT NULL REFERENCES courses(id),
    grade float CHECK (grade BETWEEN 0 AND 100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT uq_transcript_course UNIQUE (transcript_id, course_id)
);

CREATE TABLE IF NOT EXISTS tests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type  varchar(10) CHECK (type in ('MIDTERM', 'QUIZ', 'FINAL')) UNIQUE NOT NULL,
    percentage  float CHECK (percentage between 0 and 100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_results( 
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_result_id INT REFERENCES  course_results(id),
    test_id     INT  REFERENCES tests(id) NOT NULL,
    grade    float CHECK (grade between 0 and 100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);