CREATE TABLE IF NOT EXISTS transcripts(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
student_id INT REFERENCES students (id),
gpa  float,
cgpa  float,
result_date      date,
CONSTRAINT uq_student_course UNIQUE (student_id, course_id)
);
CREATE TABLE IF NOT EXISTS course_results(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_id INT REFERENCES courses(id),
transcript_id INT REFERENCES transcripts(id),
grade decimal(5,2) check (grade between 0 and 100),
CONSTRAINT uq_student_course UNIQUE (student_id, course_id)
);
CREATE TABLE IF NOT EXISTS tests (
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
type  varchar(50) NOT NULL,
percentage  decimal(5,2) check (percentage between 0 and 100) NOT NULL
student_id INTEGER NOT NULL REFERENCES student(id)
);

CREATE TABLE IF NOT EXISTS test_results( 
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
course_result_id INT REFERENCES  course_results(id),
test_result_id     INT REFERENCES tests(id),
grade    decimal(5,2) check (grade between 0 and 100) NOT NULL
);