CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_name VARCHAR(100) NOT NULL,
    l_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) CHECK (status IN ('active', 'inactive', 'graduated', 'suspended')),
    program_id INT REFERENCES programs(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE  IF NOT EXISTS instructors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT REFERENCES departments(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    honorifics VARCHAR(20),
    phone VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    group_number INT NOT NULL,
    instructor_id INT REFERENCES instructors(id) NOT NULL,
    course_id INT REFERENCES courses(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_groups(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT REFERENCES students(id),
    group_id INT REFERENCES groups(id)
);