CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    f_name VARCHAR(255) NOT NULL,
    l_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('active', 'inactive', 'graduated', 'suspended')),
    program_id INT REFERENCES programs(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE  IF NOT EXISTS instructors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT REFERENCES departments(id),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    honorifics VARCHAR(255),
    phone VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    group_number INT NOT NULL,
    instructor_id INT REFERENCES instructors(id) NOT NULL,
    course_id INT REFERENCES courses(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_groups(
    student_id INT REFERENCES students(id),
    group_id INT REFERENCES groups(id),
    CONSTRAINT pk_student_group PRIMARY KEY (student_id, group_id)
);

ALTER TABLE students
ADD email VARCHAR(255) UNIQUE;

ALTER TABLE student_groups
ADD attendance INT DEFAULT 0;

ALTER TABLE students
ADD warnings INT DEFAULT 0;
