CREATE TABLE IF NOT EXISTS groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    group_number INT NOT NULL,
    instructor_id INT REFERENCES instructors(id) NOT NULL,
    course_id INT REFERENCES courses(id) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

