CREATE TABLE IF NOT EXIST group(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    Number int NOT NULL,
    instructor_id INT REFERENCES instructor(id)
    course_id INT REFERENCES course(id) NOT NULL,

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

