CREATE TABLE  IF NOT EXISTS instructors(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT REFERENCES departments(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    honorifics VARCHAR(20),
    phone VARCHAR(15)
);