CREATE TABLE  IF NOT EXISTS instructor(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT,
    FOREIGN KEY (department_id) REFERENCES department(id),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
    honorifics VARCHAR(20),
    phone VARCHAR(15)
);